name: imersao-full-cycle
include:
  - ../../mongo/docker-compose.yaml
  - ../../kafka/docker-compose.yaml
services:
  nest_js:
    container_name: nest-api
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - kafka
